export const narrators = [
  "Abbad ibn Tamim",
  "Abbas ibn Abd al-Muttalib",
  "Abd al-Rahman ibn Awf",
  "Abdullah ibn Abbas",
  "Abdullah ibn Amr ibn al-Aas",
  "Abdullah ibn Jafar",
  "Abdullah ibn Mas'ud",
  "Abdullah ibn Umar",
  "Abdullah ibn Zaid",
  "Abdur Rahman ibn Abu Bakra",
  "Abu Ayyub al-Ansari",
  "Abu Bakr as-Siddiq",
  "Abu Barza al-Aslami",
  "Abu Darda",
  "Abu Huraira",
  "Abu Musa al-Ash'ari",
  "Abu Qatada",
  "Abu Sa’eed al-Khudri",
  "Abu Salama",
  "Abu Sufyan",
  "Abu Umama",
  "Aisha bint Abi Bakr",
  "Ali ibn Abi Talib",
  "Amr ibn al-Aas",
  "Anas ibn Malik",
  "Asma bint Abi Bakr",
  "Bilal ibn Rabah",
  "Burayda ibn al-Husayb",
  "Fatima bint Muhammad",
  "Hafsa bint Umar",
  "Hamza ibn Abd al-Muttalib",
  "Ibn Abbas",
  "Ibn Umar",
  "Jabir ibn Abdullah",
  "Khabbab ibn al-Aratt",
  "Malik ibn al-Huwayrith",
  "Muadh ibn Jabal",
  "Sa’d ibn Abi Waqqas",
  "Salman al-Farsi",
  "Talha ibn Ubaydullah",
  "Ubadah ibn as-Samit",
  "Umar ibn al-Khattab",
  "Umm Salama",
  "Uqba ibn Amr",
  "Usama ibn Zayd",
  "Uthman ibn Affan",
  "Yahya ibn Ma'mar",
  "Yahya ibn Yamur",
  "Yazid al-Faqir",
  "Zayd ibn Thabit",
  "Zubair ibn al-Awwam"
] as const;

export type NarratorType = typeof narrators[number];
