export const chapters = [
  { title: 'Introduction', slug: 'introduction', range: [1, 7] },
  { title: 'La Foi', slug: 'la-foi', range: [8, 222] },
  { title: 'Purification', slug: 'purification', range: [223, 292] },
  { title: 'Menstruations', slug: 'menstruations', range: [293, 376] },
  { title: 'Prières', slug: 'prieres', range: [377, 519] },
  { title: 'Mosquées et lieux de prière', slug: 'mosquees-et-lieux-de-priere', range: [520, 684], },
  { title: 'Prière du voyageur', slug: 'priere-du-voyageur', range: [685, 843] },
  { title: 'Prière du vendredi', slug: 'priere-du-vendredi', range: [844, 883] },
  { title: 'Prière des deux fêtes', slug: 'priere-des-deux-fetes', range: [884, 893] },
  { title: 'Prière pour la pluie', slug: 'priere-pour-la-pluie', range: [894, 900] },
  { title: 'Prière des éclipses', slug: 'priere-des-eclipses', range: [901, 915] },
  { title: 'Prière des funérailles', slug: 'priere-des-funerailles', range: [916, 978] },
  { title: 'Zakat', slug: 'zakat', range: [979, 1078] },
  { title: 'Jeûne', slug: 'jeune', range: [1079, 1170] },
  { title: 'Retraite spirituelle', slug: 'retraite-spirituelle', range: [1171, 1176] },
  { title: 'Pèlerinage', slug: 'pelerinage', range: [1177, 1399] },
  { title: 'Mariage', slug: 'mariage', range: [1400, 1443] },
  { title: 'Allaitement', slug: 'allaitement', range: [1444, 1470] },
  { title: 'Divorce', slug: 'divorce', range: [1471, 1491] },
  { title: 'Invoquer des malédictions', slug: 'invoquer-des-maledictions', range: [1492, 1500], },
  { title: 'Affranchissement', slug: 'affranchissement', range: [1501, 1510] },
  { title: 'Transactions', slug: 'transactions', range: [1511, 1550] },
  { title: 'Irrigations', slug: 'irrigations', range: [1551, 1613] },
  { title: 'Successions', slug: 'successions', range: [1614, 1619] },
  { title: 'Donations', slug: 'donations', range: [1620, 1626] },
  { title: 'Testaments', slug: 'testaments', range: [1627, 1637] },
  { title: 'Voeux', slug: 'voeux', range: [1638, 1645] },
  { title: 'Serments', slug: 'serments', range: [1646, 1668] },
  { title: 'Serments collectifs', slug: 'serments-collectifs', range: [1669, 1683] },
  { title: 'Peines légales', slug: 'peines-legales', range: [1684, 1710] },
  { title: 'Jugements', slug: 'jugements', range: [1477, 1721] },
  { title: 'Objets trouvés', slug: 'objets-trouves', range: [1722, 1729] },
  { title: 'Jihad et Expéditions', slug: 'jihad-et-expeditions', range: [1730, 1817] },
  { title: 'Commandements', slug: 'commandements', range: [1818, 1928] },
] as const;
