export const narrators = [
  "Abbad ibn Tamim",
  "Abbas ibn Abd al-Muttalib",
  "Abd al-Rahman ibn Awf",
  "Abdullah ibn Abbas",
  "Abdullah ibn Amr ibn al-Aas",
  "Abdullah ibn Jafar",
  "Abdullah ibn Mas'ud",
  "Abdullah ibn Omar",
  "Abdullah ibn Zaid",
  "Abdur Rahman ibn Abou Bakra",
  "Abou Ayyub al Ansari",
  "Abou Bakr as-Siddiq",
  "Abou Bakr ibn Abou Shaiba",
  "Abou Barza al-Aslami",
  "Abou Darda",
  "Abou Huraira",
  "Abou Musa al-Ash'ari",
  "Abou Qatada",
  "Abou Sa'id al-Khudri",
  "Abou Salama",
  "Abou Sufyan",
  "Abou Umama",
  "Aisha bint Abi Bakr",
  "Ali ibn Abi Talib",
  "Ali ibn Rabi'ah",
  "Amr ibn al-Aas",
  "Anas ibn Malik",
  "Asma bint Abi Bakr",
  "Bilal ibn Rabah",
  "Burayda ibn al-Husayb",
  "Fatima bint Muhammad",
  "Hafsa bint Omar",
  "Hamza ibn Abd al-Muttalib",
  "Jabir ibn Abdullah",
  "Khabbab ibn al-Aratt",
  "Malik ibn al-Huwayrith",
  "Muadh ibn Jabal",
  "Sa'd ibn Abi Waqqas",
  "Salman al-Farsi",
  "Talha ibn Ubayd Allah",
  "Ubadah ibn as-Samit",
  "Omar ibn al-Khattab",
  "Umm Salama",
  "Uqba ibn Amr",
  "Usama ibn Zayd",
  "Uthman ibn Affan",
  "Yahya ibn Ma'mar",
  "Yahya ibn Yamur",
  "Yazid al-Faqir",
  "Zayd ibn Thabit",
  "Zubair ibn al-Awwam",
] as const;
