export const narrators = [
  { name: 'Abbad ibn Tamim', slug: 'abbad-ibn-tamim' },
  { name: 'Abbas ibn Abd al-Muttalib', slug: 'abbas-ibn-abd-al-muttalib' },
  { name: 'Abd al-Rahman ibn Awf', slug: 'abd-al-rahman-ibn-awf' },
  { name: 'Abdullah ibn Abbas', slug: 'abdullah-ibn-abbas' },
  { name: 'Abdullah ibn Amr ibn al-Aas', slug: 'abdullah-ibn-amr-ibn-al-aas' },
  { name: 'Abdullah ibn Jafar', slug: 'abdullah-ibn-jafar' },
  { name: "Abdullah ibn Mas'ud", slug: 'abdullah-ibn-masud' },
  { name: 'Abdullah ibn Umar', slug: 'abdullah-ibn-umar' },
  { name: 'Abdullah ibn Zaid', slug: 'abdullah-ibn-zaid' },
  { name: 'Abdur Rahman ibn Abou Bakra', slug: 'abdur-rahman-ibn-abou-bakra' },
  { name: 'Abou Ayyub al-Ansari', slug: 'abou-ayyub-al-ansari' },
  { name: 'Abou Bakr as-Siddiq', slug: 'abou-bakr-as-siddiq' },
  { name: 'Abou Bakr ibn Abou Shaiba', slug: 'abou-bakr-ibn-abou-shaiba' },
  { name: 'Abou Barza al-Aslami', slug: 'abou-barza-al-aslami' },
  { name: 'Abou Darda', slug: 'abou-darda' },
  { name: 'Abou Huraira', slug: 'abou-huraira' },
  { name: "Abou Musa al-Ash'ari", slug: 'abou-musa-al-ashari' },
  { name: 'Abou Qatada', slug: 'abou-qatada' },
  { name: "Abou Sa'id al-Khudri", slug: 'abou-said-al-khudri' },
  { name: 'Abou Salama', slug: 'abou-salama' },
  { name: 'Abou Sufyan', slug: 'abou-sufyan' },
  { name: 'Abou Umama', slug: 'abou-umama' },
  { name: 'Aisha bint Abi Bakr', slug: 'aisha-bint-abi-bakr' },
  { name: 'Ali ibn Abi Talib', slug: 'ali-ibn-abi-talib' },
  { name: 'Amr ibn al-Aas', slug: 'amr-ibn-al-aas' },
  { name: 'Anas ibn Malik', slug: 'anas-ibn-malik' },
  { name: 'Asma bint Abi Bakr', slug: 'asma-bint-abi-bakr' },
  { name: 'Bilal ibn Rabah', slug: 'bilal-ibn-rabah' },
  { name: 'Burayda ibn al-Husayb', slug: 'burayda-ibn-al-husayb' },
  { name: 'Fatima bint Muhammad', slug: 'fatima-bint-muhammad' },
  { name: 'Hafsa bint Umar', slug: 'hafsa-bint-umar' },
  { name: 'Hamza ibn Abd al-Muttalib', slug: 'hamza-ibn-abd-al-muttalib' },
  { name: 'Ibn Abbas', slug: 'ibn-abbas' },
  { name: 'Ibn Umar', slug: 'ibn-umar' },
  { name: 'Jabir ibn Abdullah', slug: 'jabir-ibn-abdullah' },
  { name: 'Khabbab ibn al-Aratt', slug: 'khabbab-ibn-al-aratt' },
  { name: 'Malik ibn al-Huwayrith', slug: 'malik-ibn-al-huwayrith' },
  { name: 'Muadh ibn Jabal', slug: 'muadh-ibn-jabal' },
  { name: "Sa'd ibn Abi Waqqas", slug: 'sad-ibn-abi-waqqas' },
  { name: 'Salman al-Farsi', slug: 'salman-al-farsi' },
  { name: 'Talha ibn Ubaydullah', slug: 'talha-ibn-ubaydullah' },
  { name: 'Ubadah ibn as-Samit', slug: 'ubadah-ibn-as-samit' },
  { name: 'Umar ibn al-Khattab', slug: 'umar-ibn-al-khattab' },
  { name: 'Umm Salama', slug: 'umm-salama' },
  { name: 'Uqba ibn Amr', slug: 'uqba-ibn-amr' },
  { name: 'Usama ibn Zayd', slug: 'usama-ibn-zayd' },
  { name: 'Uthman ibn Affan', slug: 'uthman-ibn-affan' },
  { name: "Yahya ibn Ma'mar", slug: 'yahya-ibn-mamar' },
  { name: 'Yahya ibn Yamur', slug: 'yahya-ibn-yamur' },
  { name: 'Yazid al-Faqir', slug: 'yazid-al-faqir' },
  { name: 'Zayd ibn Thabit', slug: 'zayd-ibn-thabit' },
  { name: 'Zubair ibn al-Awwam', slug: 'zubair-ibn-al-awwam' },
] as const;
