export const sahabas = [
  "Abou Bakr As-Siddiq",
  "Omar ibn al-Khattab",
  "Uthman ibn Affan",
  "Ali ibn Abi Talib",
  "Abou Huraira",
  "Abdallah ibn Abbas",
  "Abou Dharr Al-Ghifari",
  "Bilal ibn Rabah",
  "Salman Al-Farsi",
  "Zayd ibn Harithah",
  "Hassan ibn Ali",
  "Fatimah bint Muhammad",
  "Anas ibn Malik",
  "Abou Talib",
  "Abdullah ibn Umar",
  "Abou Ayyub Al-Ansari",
  "Abou Muslim Al-Khawlani",
  "Ma'bad Al Jouhani",
  "Houmayd ibn Abder Rahman Al Houmayri",
  "Abdallah ibn Omar",
];
