export const sahabas = [
  "Abdallah ibn Omar",
  "Abdallah ibn Abi Umayya",
  "Abdallah ibn Abbas",
  "Abou Bakr As-Siddiq",
  "Abou Darda",
  "Abou Huraira",
  "Abou Talib",
  "Abou Ayyub Al-Ansari",
  "Abou Dharr Al-Ghifari",
  "Abou Muslim Al-Khawlani",
  "Al-Ashajj Abd al-Qays",
  "Al Mughirah ibn Shu'bah",
  "Ali ibn Abi Talib",
  "Anas ibn Malik",
  "Bilal ibn Rabah",
  "Fatimah bint Muhammad",
  "Hassan ibn Ali",
  "Houmayd ibn Abder Rahman Al Houmayri",
  "Omar ibn al-Khattab",
  "Othman ibn Affan",
  "Ma'bad Al Jouhani",
  "Muadh ibn Jabal",
  "Mujahid ibn Jabr",
  "Nou'man ibn Qawqal",
  "Salman Al-Farsi",
  "Zayd ibn Harithah",
];
